services:
    soil_comment_digest.command.comments_digest:
        class: Soil\CommentsDigestBundle\Command\CommentsDigest
        arguments: [@soil_comment_digest.model.comments_model, @soil_comment_digest.service.subscribers_miner, @soil_comment_digest.service.comment_censor, @soil_notification.service.notification]
        calls:
            - [setLogger, [@logger]]
            - [setConfigInfo, ["Notification mail_gateway", %mail_gateway%]]
        tags:
            - { name: console.command }
            - { name: monolog.logger, channel: queue }

    soil_comment_digest.service.brief_property_setter:
        class: Soil\CommentsDigestBundle\Service\BriefPropertySetter
        arguments: [@soil_discover.service.resolver]

    soil_comment_digest.service.subscribers_miner:
        class: Soil\CommentsDigestBundle\Service\SubscribersMiner
        arguments: []
        calls:
            - [addMiner, [@soil_comment_digest.subscribers_miner.entity_authors_miner]]
            - [addMiner, [@soil_comment_digest.subscribers_miner.answers_miner]]
            - [setAckService, [@soil_ack_service.service.ack]]
            - [setLogger, [@logger]]
        tags:
            - { name: monolog.logger, channel: queue }


    soil_comment_digest.model.comments_model:
        class: Soil\CommentsDigestBundle\Model\CommentsModel
        arguments: [@soil_rdf_processor.sparql_client, %semantic_namespaces%]
        tags:
            -  { name: soil_semantic_repository_model }




    soil_comment_digest.service.comment_censor:
        class: Soil\CommentsDigestBundle\Service\SubscribersReducer
        arguments: []
        calls:
            - [addReducer, [@soil_comment_digest.subscribers_reducer.unique_reducer]]


    soil_comment_digest.subscribers_reducer.unique_reducer:
        class: Soil\CommentsDigestBundle\SubscribersReducer\UniqueReducer
        tags:
            -  { name: soil_comments_digest.subscribers_reducer }





    soil_comment_digest.subscribers_miner.entity_authors_miner:
        class: Soil\CommentsDigestBundle\SubscribersMiner\EntityAuthorsMiner
        arguments: [@soil_comment_digest.service.brief_property_setter]
        calls:
            - [setEndpoint, [@soil_rdf_processor.sparql_client]]
        tags:
            -  { name: soil_comments_digest.subscribers_miner }



    soil_comment_digest.subscribers_miner.answers_miner:
        class: Soil\CommentsDigestBundle\SubscribersMiner\AnswersMiner
        arguments: [@soil_comment_digest.service.brief_property_setter]
        calls:
            - [setEndpoint, [@soil_rdf_processor.sparql_client]]
        tags:
            -  { name: soil_comments_digest.subscribers_miner }
